// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zocyuiyewjmmrpzqyqua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvY3l1aXlld2ptbXJwenF5cXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzMzMTgsImV4cCI6MjA2MjgwOTMxOH0.Q6PmCEpyqXR5xWW3yBEuePBmGZY3TO3nXgg-8s_UJi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);